config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_for :users

  resources :maps do
    get 'markers', :defaults => { :format => 'json' }
    post 'marker', :defaults => { :format => 'json' }
  end

  root :to => 'application#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/map.rb
class Map < ApplicationRecord
  has_many :markers

  validates :lat1, numericality: { greater_than_or_equal_to:  -90, less_than_or_equal_to:  90 }
  validates :lon1, numericality: { greater_than_or_equal_to: -180, less_than_or_equal_to: 180 }
  validates :lat2, numericality: { greater_than_or_equal_to:  -90, less_than_or_equal_to:  90 }
  validates :lon2, numericality: { greater_than_or_equal_to: -180, less_than_or_equal_to: 180 }

end

app/models/marker.rb
class Marker < ApplicationRecord
  validates :lat, numericality: { greater_than_or_equal_to:  -90, less_than_or_equal_to:  90 }
  validates :lon, numericality: { greater_than_or_equal_to: -180, less_than_or_equal_to: 180 }

  validates :map_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable, :rememberable, :validatable, :authentication_keys => [:email]

  has_many :maps
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!

  def index
    redirect_to maps_path if user_signed_in?
    # @user_data = UserSerializer.new(current_user) if current_user
  end

end

app/controllers/maps_controller.rb
class MapsController <  ApplicationController
  def index
    @maps = current_user.maps
  end

  def new
    @map = Map.new
  end

  def create
    @map = Map.new(map_params)

    if @map.save
      redirect_to :maps
    else
      flash.now[:error] = @map.errors.full_messages
      render action: 'new'
    end
  end

  def destroy
    map.destroy
    redirect_to :maps
  end

  def edit
    map
  end

  def marker
    @marker = Marker.create(marker_params.merge(:map_id => params[:map_id]))
    render json: @marker
  end

  def markers
    render json: map_markers
  end

  def show
    map
    @markers = map.markers
    @marker = Marker.new(:map_id => map.id)
  end

  def update
    map.update_attributes(map_params)
    redirect_to :maps
  end

  private

  def map
    @map ||= Map.find(params[:id])
  end

  def map_markers
    Map.find(params[:map_id]).markers
  end

  def map_params
    params.require(:map).permit(:title, :lon1, :lat1, :lon2, :lat2).merge(:user_id => current_user.id)
  end

  def marker_params
    params.require(:marker).permit(:name, :description, :residents, :lat, :lon)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/index.html.erb
Loading...

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset=utf-8 />
    <title>Mapit</title>
    <meta name='viewport' content='initial-scale=1,maximum-scale=1,user-scalable=no' />
    <%= csrf_meta_tags %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
    <script src='https://api.mapbox.com/mapbox.js/v2.4.0/mapbox.js'></script>
    <link href='https://api.mapbox.com/mapbox.js/v2.4.0/mapbox.css' rel='stylesheet' />
    <%= stylesheet_link_tag 'application', :media => 'all', 'data-turbolinks-track' => 'reload' %>
    <%= render '/global_vars' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>

</html>

app/views/maps/_map_form.html.erb
<%= form_for(@map) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title, class: 'form-control' %>

  <%= f.label :lon1 %>
  <%= f.text_field :lon1, class: 'form-control' %>

  <%= f.label :lat1 %>
  <%= f.text_field :lat1, class: 'form-control' %>

  <%= f.label :lon2 %>
  <%= f.text_field :lon2, class: 'form-control' %>

  <%= f.label :lat2 %>
  <%= f.text_field :lat2, class: 'form-control' %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>

<% end %>

app/views/maps/_marker_form.html.erb
<div id="map_id" data="<%= @marker.map_id %>"/>

<%= form_for(@marker, :url => url_for(:controller => 'maps', :action => 'marker', :map_id => @marker.map_id), :html => {:id => 'marker_form'}) do |f| %>
  <div class="row">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="row">
    <%= f.label :description %>
    <%= f.text_area :description, class: 'form-control' %>
  </div>

  <div class="row">
    <%= f.label :residents %>
    <%= f.text_field :residents, class: 'form-control' %>
  </div>

  <div class="row">
    <%= f.submit 'Save marker', id: 'save_button', class: "btn btn-primary" %>
  </div>

<% end %>

app/views/maps/edit.html.erb
<% provide(:title, 'Edit Map') %>
<% provide(:button_text, 'Save') %>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'map_form' %>
  </div>
</div>

app/views/maps/index.html.erb
<table>
  <tr>
    <th>Action</th>
    <th>Thumb</th>
    <th>Title/Coordinates</th>
  </tr>

  <% @maps.each_with_index do |map, index| %>
    <tr>
      <td>
        <button><a href="<%= edit_map_path(map) %>">Edit</a></button>
        <button>
          <%= link_to "Delete", map_path(map), method: :delete, data: { confirm: 'Are you sure?' } %>
        </button>
      </td>
      <td id="map<%= index %>" data-map="<%= map.to_json %>" class="map-thumb"></td>
      <td>
        <% if map.title %>
          <%= map.title %>
        <% else %>
          (<%= map.lon1 %>,<%= map.lat1 %>) - (<%= map.lon2 %>,<%= map.lat2 %>)
        <% end %>
      </td>
    </tr>
  <% end %>
</table>

<div>
  <button><%= link_to "Add", new_map_path %></button>
</div>

<script>
  var maps = [];

  $(document).ready(function() {
    $('.map-thumb').each(function(index) {
      var data = $(this).data('map');
      maps[index] = L.mapbox.map('map' + index, 'mapbox.streets')
          .setView([data.lon1, data.lat1], 4);

      maps[index].fitBounds([[data.lon1, data.lat1], [data.lon2, data.lat2]]);
    });

    $('.map-thumb').click(function() {
      var data = $(this).data('map');
      window.location = '/maps/' + data.id;
    })
  });
</script>

app/views/maps/new.html.erb
<% provide(:title, 'New Map') %>
<% provide(:button_text, 'Save') %>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'map_form' %>
  </div>
</div>

app/views/maps/show.html.erb
<div class="map-wrapper">
  <div class="button-wrapper">
    <button><a href="/maps">Back</a></button>
  </div>
  <div id='map' class="map-large" data-map="<%= @map.to_json(:include => :markers) %>"/>
</div>
<div id="marker-message" style="display:none;"></div>
<div id="marker-wrapper" style="display:none;">
  <%= render 'marker_form' %>
</div>

<script>

  var data = $('#map').data('map');

  var map = L.mapbox.map('map', 'mapbox.streets')
      .setView([data.lon1, data.lat1], 9);

  map.fitBounds([[data.lon1, data.lat1], [data.lon2, data.lat2]]);

  var markers = data.markers;

  $(markers).each(function (index) {
    var point = L.latLng(this.lat, this.lon);
    var marker = new L.marker(point, {title: markerText(this)}).addTo(map);
  });

  map.on('click', function (e) {
    var marker = new L.marker(e.latlng).addTo(map);

    $('#marker_form')[0].reset();
    $('#marker-message').show();
    $('#marker-message').html("Please enter data for marker:<br>");
    $('#marker-wrapper').show();

    // ToDo: expose modal here, don't create marker until success

    // ToDo: handle popUp for new marker, deletion of unsaved marker

    $('#save_button').one("click", function () {
      console.log("Save Button clicked");

      var map_id = $('#map_id').data();
      var form = $('#marker_form');
      var data = form.serialize();

      data = data + "&marker%5Blat%5D=" + e.latlng.lat + "&marker%5Blon%5D=" + e.latlng.lng;

      $.ajax({
        method: "POST",
        url: form.attr('action'),
        data: data,
        dataType: 'json'
      }).done(function (msg) {
        $('#marker-wrapper').hide();
        $('#marker-message').html("Marker saved, please reload to see updated hover.");
        setTimeout(function() {
          $('#marker-message').hide();
        }, 1000);
      });
      return false;

    });

    $('#save_button').click(function () {
      return false;
    });
  });

  function markerText(obj) {
    var text = "";
    if (obj.name) {
      text = obj.name;
    }
    if (obj.description) {
      if (text.length) {
        text += ", ";
      }
      text += obj.description;
    }
    if (obj.residents) {
      if (text.length) {
        text += ", ";
      }
      text += "residents: " + obj.residents;
    }
    return text;
  }

</script>